"""Initial migration with User, Usage, and AIToolConfig models

Revision ID: 55726d8f239e
Revises: 
Create Date: 2025-09-25 02:50:35.730170

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55726d8f239e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.Enum('FREE', 'PREMIUM', name='userrole'), nullable=False, server_default='FREE'))
        batch_op.add_column(sa.Column('plan_type', sa.Enum('MONTHLY', 'YEARLY', 'LIFETIME', name='plantype'), nullable=True))
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=128),
               existing_nullable=False)
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.create_unique_constraint('uq_users_username', ['username'])
        batch_op.create_unique_constraint('uq_users_email', ['email'])
        batch_op.drop_column('is_admin')
        batch_op.drop_column('last_name')
        batch_op.drop_column('first_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_name', sa.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('last_name', sa.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('is_admin', sa.BOOLEAN(), nullable=False))
        batch_op.drop_constraint('uq_users_email', type_='unique')
        batch_op.drop_constraint('uq_users_username', type_='unique')
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=1)
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=1)
        batch_op.alter_column('password_hash',
               existing_type=sa.String(length=128),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
        batch_op.drop_column('plan_type')
        batch_op.drop_column('role')

    # ### end Alembic commands ###
